LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE := F-Droid
LOCAL_MODULE_TAGS := optional
LOCAL_PACKAGE_NAME := F-Droid
LOCAL_SRC_FILE := FDroid.apk

LOCAL_PRIVILEGED_MODULE := true
LOCAL_CERTIFICATE := PRESIGNED

LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)

$(LOCAL_PATH)/$(LOCAL_SRC_FILE):
				cd $(LOCAL_PATH) && bash get-prebuilt

include $(BUILD_PREBUILT)

